apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-data-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods can read
  resources:
    requests:
      storage: 5Gi  # Adjust based on your data size
  storageClassName: standard  # Minikube's default storage class
