# replicaCount: 1

# postgresql:
#   enabled: false

# image:
#   repository: burakince/mlflow
#   pullPolicy: IfNotPresent
#   tag: ""

# service:
#   enabled: true
#   type: ClusterIP
#   port: 80
#   containerPort: 5000

# log:
#   enabled: true
#   level: info

# telemetry:
#   enabled: false

# backendStore:
#   databaseMigration: true
#   database:
#     host: postgres-postgresql.airflow.svc.cluster.local
#     port: 5432
#     database: mlflow
#     user: mlflow
#     password: cG9zdGdyZXMxMjM=
  


# # artifactRoot:
# #   proxiedArtifactStorage: false
# #   defaultArtifactRoot: /mlflow/artifacts
# #   defaultArtifactsDestination: /mlflow/artifacts

# auth:
#   enabled: false

# resources: {}

# #persistent Volume Claim for MLflow artifacts
# extraVolumes:
#   - name: pipeline-data
#     persistentVolumeClaim:
#       claimName: pipeline-data

# extraVolumeMounts:
#   - name: pipeline-data
#     mountPath: /data
    
# extraArgs:
#   - --default-artifact-root=file:/data/mlflow_artifacts


postgresql:
  enabled: false
minio:
  enabled: false

tracking:
  auth:
    enabled: false
    
backendStore:
  databaseMigration: true
  database:
    host: postgres-postgresql.airflow.svc.cluster.local
    port: 5432
    database: mlflow
    user: mlflow
    password: cG9zdGdyZXMxMjM=

extraVolumes:
  - name: pipeline-data
    persistentVolumeClaim:
      claimName: pipeline-data

extraVolumeMounts:
  - name: pipeline-data
    mountPath: /data

extraArgs:
  - --default-artifact-root=file:/data/mlflow_artifacts
